<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="Mohit" failures="2" tests="2" name="Smoke" time="22.042" errors="0" timestamp="2025-03-30T23:42:32 IST">
  <testcase classname="Selenium.Testpackage.ErrorValidationTest" name="validateSignout" time="5.725">
    <failure type="java.lang.AssertionError" message="expected [LogoutSuccessfully] but found [Logout Successfully]">
      <![CDATA[java.lang.AssertionError: expected [LogoutSuccessfully] but found [Logout Successfully]
at Selenium.Testpackage.ErrorValidationTest.validateSignout(ErrorValidationTest.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- validateSignout -->
  <testcase classname="Selenium.Testpackage.ErrorValidationTest" name="validateSignout" time="14.673">
    <failure type="java.lang.AssertionError" message="expected [LogoutSuccessfully] but found [Logout Successfully]">
      <![CDATA[java.lang.AssertionError: expected [LogoutSuccessfully] but found [Logout Successfully]
at Selenium.Testpackage.ErrorValidationTest.validateSignout(ErrorValidationTest.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- validateSignout -->
  <testcase classname="Selenium.Testpackage.ErrorValidationTest" name="validatecartProduct" time="0.0">
    <ignored/>
  </testcase> <!-- validatecartProduct -->
  <testcase classname="Selenium.Testpackage.ErrorValidationTest" name="validateOrderConfirmation" time="0.0">
    <ignored/>
  </testcase> <!-- validateOrderConfirmation -->
</testsuite> <!-- Smoke -->
